"""Adiciona campo ativo ao usuario

Revision ID: 7802f6c48547
Revises: 133428575ed5
Create Date: 2025-11-07 14:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7802f6c48547'
down_revision = '133428575ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        # Adiciona a coluna com um valor padrão no lado do servidor.
        # '1' é tratado como True em SQLite.
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('ativo')
    # ### end Alembic commands ###
