"""Criação inicial

Revision ID: 91891817e852
Revises: 
Create Date: 2025-10-31 15:19:18.396821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91891817e852'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('unidade', sa.String(length=50), nullable=False),
    sa.Column('filial', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('fabricante', sa.String(length=50), nullable=True),
    sa.Column('ano', sa.String(length=4), nullable=True),
    sa.Column('km_atual', sa.Integer(), nullable=True),
    sa.Column('data_ultima_atualizacao_km', sa.DateTime(), nullable=True),
    sa.Column('data_calibragem', sa.Date(), nullable=True),
    sa.Column('data_proxima_calibragem', sa.Date(), nullable=True),
    sa.Column('data_proxima_revisao_carreta', sa.Date(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('em_manutencao', sa.Boolean(), nullable=True),
    sa.Column('km_troca_preventiva', sa.Integer(), nullable=True),
    sa.Column('km_ultima_revisao_preventiva', sa.Integer(), nullable=True),
    sa.Column('data_ultima_revisao_preventiva', sa.Date(), nullable=True),
    sa.Column('km_troca_intermediaria', sa.Integer(), nullable=True),
    sa.Column('km_ultima_revisao_intermediaria', sa.Integer(), nullable=True),
    sa.Column('data_ultima_revisao_intermediaria', sa.Date(), nullable=True),
    sa.Column('intervalo_oleo_diferencial', sa.Integer(), nullable=True),
    sa.Column('troca_oleo_diferencial', sa.Integer(), nullable=True),
    sa.Column('data_troca_oleo_diferencial', sa.Date(), nullable=True),
    sa.Column('intervalo_oleo_cambio', sa.Integer(), nullable=True),
    sa.Column('troca_oleo_cambio', sa.Integer(), nullable=True),
    sa.Column('data_troca_oleo_cambio', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('unidade', sa.String(length=50), nullable=True),
    sa.Column('filial', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('logs_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=200), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manutencoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('km_realizado', sa.Integer(), nullable=True),
    sa.Column('data_troca', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['placa_id'], ['placas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_conjunto', sa.String(length=100), nullable=False),
    sa.Column('unidade', sa.String(length=100), nullable=True),
    sa.Column('filial', sa.String(length=100), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('placa_cavalo_id', sa.Integer(), nullable=True),
    sa.Column('placa_carreta1_id', sa.Integer(), nullable=True),
    sa.Column('placa_carreta2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['placa_carreta1_id'], ['placas.id'], ),
    sa.ForeignKeyConstraint(['placa_carreta2_id'], ['placas.id'], ),
    sa.ForeignKeyConstraint(['placa_cavalo_id'], ['placas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_conjunto')
    )
    op.create_table('historico_bloqueios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa_id', sa.Integer(), nullable=False),
    sa.Column('tipo_manutencao', sa.String(length=100), nullable=False),
    sa.Column('data_bloqueio', sa.DateTime(), nullable=False),
    sa.Column('km_bloqueio', sa.Integer(), nullable=False),
    sa.Column('liberado', sa.Boolean(), nullable=True),
    sa.Column('data_liberacao', sa.DateTime(), nullable=True),
    sa.Column('manutencao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manutencao_id'], ['manutencoes.id'], ),
    sa.ForeignKeyConstraint(['placa_id'], ['placas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('cnh', sa.String(length=20), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('unidade', sa.String(length=50), nullable=True),
    sa.Column('filial', sa.String(length=50), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('veiculos_indisponibilidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('data_indisponibilidade', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculos_indisponibilidade')
    op.drop_table('motoristas')
    op.drop_table('historico_bloqueios')
    op.drop_table('veiculos')
    op.drop_table('manutencoes')
    op.drop_table('logs_sistema')
    op.drop_table('usuarios')
    op.drop_table('placas')
    # ### end Alembic commands ###
