"""Adiciona campos de finalizacao a SolicitacaoServico

Revision ID: ade4b2d252e9
Revises: 7802f6c48547
Create Date: 2025-11-07 14:07:07.396199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade4b2d252e9'
down_revision = '7802f6c48547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_os', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('observacao_interna', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes_servico', schema=None) as batch_op:
        batch_op.drop_column('observacao_interna')
        batch_op.drop_column('numero_os')

    # ### end Alembic commands ###
